/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserCompact from './UserCompact';

/**
 * The CustomFieldResponseAllOf model module.
 * @module model/CustomFieldResponseAllOf
 * @version 1.0.0
 */
class CustomFieldResponseAllOf {
    /**
     * Constructs a new <code>CustomFieldResponseAllOf</code>.
     * @alias module:model/CustomFieldResponseAllOf
     */
    constructor() { 
        
        CustomFieldResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomFieldResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomFieldResponseAllOf} obj Optional instance to populate.
     * @return {module:model/CustomFieldResponseAllOf} The populated <code>CustomFieldResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomFieldResponseAllOf();

            if (data.hasOwnProperty('created_by')) {
                obj['created_by'] = UserCompact.constructFromObject(data['created_by']);
            }
            if (data.hasOwnProperty('people_value')) {
                obj['people_value'] = ApiClient.convertToType(data['people_value'], [UserCompact]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UserCompact} created_by
 */
CustomFieldResponseAllOf.prototype['created_by'] = undefined;

/**
 * *Conditional*. Only relevant for custom fields of type `people`. This array of [compact user](/docs/user-compact) objects reflects the values of a `people` custom field.
 * @member {Array.<module:model/UserCompact>} people_value
 */
CustomFieldResponseAllOf.prototype['people_value'] = undefined;






export default CustomFieldResponseAllOf;

