/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DateVariableRequest from './DateVariableRequest';

/**
 * The ProjectTemplateInstantiateProjectRequest model module.
 * @module model/ProjectTemplateInstantiateProjectRequest
 * @version 1.0.0
 */
class ProjectTemplateInstantiateProjectRequest {
    /**
     * Constructs a new <code>ProjectTemplateInstantiateProjectRequest</code>.
     * @alias module:model/ProjectTemplateInstantiateProjectRequest
     * @param name {String} The name of the new project.
     * @param _public {Boolean} Sets the project to public to its team.
     */
    constructor(name, _public) { 
        
        ProjectTemplateInstantiateProjectRequest.initialize(this, name, _public);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, _public) { 
        obj['name'] = name;
        obj['public'] = _public;
    }

    /**
     * Constructs a <code>ProjectTemplateInstantiateProjectRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectTemplateInstantiateProjectRequest} obj Optional instance to populate.
     * @return {module:model/ProjectTemplateInstantiateProjectRequest} The populated <code>ProjectTemplateInstantiateProjectRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectTemplateInstantiateProjectRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('team')) {
                obj['team'] = ApiClient.convertToType(data['team'], 'String');
            }
            if (data.hasOwnProperty('workspace')) {
                obj['workspace'] = ApiClient.convertToType(data['workspace'], 'String');
            }
            if (data.hasOwnProperty('public')) {
                obj['public'] = ApiClient.convertToType(data['public'], 'Boolean');
            }
            if (data.hasOwnProperty('is_strict')) {
                obj['is_strict'] = ApiClient.convertToType(data['is_strict'], 'Boolean');
            }
            if (data.hasOwnProperty('requested_dates')) {
                obj['requested_dates'] = ApiClient.convertToType(data['requested_dates'], [DateVariableRequest]);
            }
        }
        return obj;
    }


}

/**
 * The name of the new project.
 * @member {String} name
 */
ProjectTemplateInstantiateProjectRequest.prototype['name'] = undefined;

/**
 * *Conditional*. Sets the team of the new project. If the project template exists in an _organization_, you must specify a value for `team` and not `workspace`.
 * @member {String} team
 */
ProjectTemplateInstantiateProjectRequest.prototype['team'] = undefined;

/**
 * *Conditional*. Sets the workspace of the new project. If the project template exists in a _workspace_, you must specify a value for `workspace` and not `team`.
 * @member {String} workspace
 */
ProjectTemplateInstantiateProjectRequest.prototype['workspace'] = undefined;

/**
 * Sets the project to public to its team.
 * @member {Boolean} public
 */
ProjectTemplateInstantiateProjectRequest.prototype['public'] = undefined;

/**
 * *Optional*. If set to `true`, the endpoint returns an \"Unprocessable Entity\" error if you fail to provide a calendar date value for any date variable. If set to `false`, a default date is used for each unfulfilled date variable (e.g., the current date is used as the Start Date of a project).
 * @member {Boolean} is_strict
 */
ProjectTemplateInstantiateProjectRequest.prototype['is_strict'] = undefined;

/**
 * Array of mappings of date variables to calendar dates.
 * @member {Array.<module:model/DateVariableRequest>} requested_dates
 */
ProjectTemplateInstantiateProjectRequest.prototype['requested_dates'] = undefined;






export default ProjectTemplateInstantiateProjectRequest;

