/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StoryResponseDates model module.
 * @module model/StoryResponseDates
 * @version 1.0.0
 */
class StoryResponseDates {
    /**
     * Constructs a new <code>StoryResponseDates</code>.
     * *Conditional*
     * @alias module:model/StoryResponseDates
     */
    constructor() { 
        
        StoryResponseDates.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StoryResponseDates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoryResponseDates} obj Optional instance to populate.
     * @return {module:model/StoryResponseDates} The populated <code>StoryResponseDates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoryResponseDates();

            if (data.hasOwnProperty('start_on')) {
                obj['start_on'] = ApiClient.convertToType(data['start_on'], 'Date');
            }
            if (data.hasOwnProperty('due_at')) {
                obj['due_at'] = ApiClient.convertToType(data['due_at'], 'Date');
            }
            if (data.hasOwnProperty('due_on')) {
                obj['due_on'] = ApiClient.convertToType(data['due_on'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} start_on
 */
StoryResponseDates.prototype['start_on'] = undefined;

/**
 * @member {Date} due_at
 */
StoryResponseDates.prototype['due_at'] = undefined;

/**
 * @member {Date} due_on
 */
StoryResponseDates.prototype['due_on'] = undefined;






export default StoryResponseDates;

