/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TeamCompact from './TeamCompact';
import TeamRequestAllOf from './TeamRequestAllOf';

/**
 * The TeamRequest model module.
 * @module model/TeamRequest
 * @version 1.0.0
 */
class TeamRequest {
    /**
     * Constructs a new <code>TeamRequest</code>.
     * @alias module:model/TeamRequest
     * @implements module:model/TeamCompact
     * @implements module:model/TeamRequestAllOf
     */
    constructor() { 
        TeamCompact.initialize(this);TeamRequestAllOf.initialize(this);
        TeamRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamRequest} obj Optional instance to populate.
     * @return {module:model/TeamRequest} The populated <code>TeamRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamRequest();
            TeamCompact.constructFromObject(data, obj);
            TeamRequestAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('gid')) {
                obj['gid'] = ApiClient.convertToType(data['gid'], 'String');
            }
            if (data.hasOwnProperty('resource_type')) {
                obj['resource_type'] = ApiClient.convertToType(data['resource_type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('html_description')) {
                obj['html_description'] = ApiClient.convertToType(data['html_description'], 'String');
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = ApiClient.convertToType(data['organization'], 'String');
            }
            if (data.hasOwnProperty('visibility')) {
                obj['visibility'] = ApiClient.convertToType(data['visibility'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Globally unique identifier of the resource, as a string.
 * @member {String} gid
 */
TeamRequest.prototype['gid'] = undefined;

/**
 * The base type of this resource.
 * @member {String} resource_type
 */
TeamRequest.prototype['resource_type'] = undefined;

/**
 * The name of the team.
 * @member {String} name
 */
TeamRequest.prototype['name'] = undefined;

/**
 * The description of the team. 
 * @member {String} description
 */
TeamRequest.prototype['description'] = undefined;

/**
 * The description of the team with formatting as HTML. 
 * @member {String} html_description
 */
TeamRequest.prototype['html_description'] = undefined;

/**
 * The organization/workspace the team belongs to. This must be the same organization you are in and cannot be changed once set. 
 * @member {String} organization
 */
TeamRequest.prototype['organization'] = undefined;

/**
 * The visibility of the team to users in the same organization 
 * @member {module:model/TeamRequest.VisibilityEnum} visibility
 */
TeamRequest.prototype['visibility'] = undefined;


// Implement TeamCompact interface:
/**
 * Globally unique identifier of the resource, as a string.
 * @member {String} gid
 */
TeamCompact.prototype['gid'] = undefined;
/**
 * The base type of this resource.
 * @member {String} resource_type
 */
TeamCompact.prototype['resource_type'] = undefined;
/**
 * The name of the team.
 * @member {String} name
 */
TeamCompact.prototype['name'] = undefined;
// Implement TeamRequestAllOf interface:
/**
 * The description of the team. 
 * @member {String} description
 */
TeamRequestAllOf.prototype['description'] = undefined;
/**
 * The description of the team with formatting as HTML. 
 * @member {String} html_description
 */
TeamRequestAllOf.prototype['html_description'] = undefined;
/**
 * The organization/workspace the team belongs to. This must be the same organization you are in and cannot be changed once set. 
 * @member {String} organization
 */
TeamRequestAllOf.prototype['organization'] = undefined;
/**
 * The visibility of the team to users in the same organization 
 * @member {module:model/TeamRequestAllOf.VisibilityEnum} visibility
 */
TeamRequestAllOf.prototype['visibility'] = undefined;



/**
 * Allowed values for the <code>visibility</code> property.
 * @enum {String}
 * @readonly
 */
TeamRequest['VisibilityEnum'] = {

    /**
     * value: "secret"
     * @const
     */
    "secret": "secret",

    /**
     * value: "request_to_join"
     * @const
     */
    "request_to_join": "request_to_join",

    /**
     * value: "public"
     * @const
     */
    "public": "public"
};



export default TeamRequest;

