/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WorkspaceCompact from './WorkspaceCompact';

/**
 * The TeamResponseAllOf model module.
 * @module model/TeamResponseAllOf
 * @version 1.0.0
 */
class TeamResponseAllOf {
    /**
     * Constructs a new <code>TeamResponseAllOf</code>.
     * @alias module:model/TeamResponseAllOf
     */
    constructor() { 
        
        TeamResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TeamResponseAllOf} obj Optional instance to populate.
     * @return {module:model/TeamResponseAllOf} The populated <code>TeamResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamResponseAllOf();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('html_description')) {
                obj['html_description'] = ApiClient.convertToType(data['html_description'], 'String');
            }
            if (data.hasOwnProperty('organization')) {
                obj['organization'] = ApiClient.convertToType(data['organization'], WorkspaceCompact);
            }
            if (data.hasOwnProperty('permalink_url')) {
                obj['permalink_url'] = ApiClient.convertToType(data['permalink_url'], 'String');
            }
            if (data.hasOwnProperty('visibility')) {
                obj['visibility'] = ApiClient.convertToType(data['visibility'], 'String');
            }
        }
        return obj;
    }


}

/**
 * [Opt In](/docs/input-output-options). The description of the team. 
 * @member {String} description
 */
TeamResponseAllOf.prototype['description'] = undefined;

/**
 * [Opt In](/docs/input-output-options). The description of the team with formatting as HTML. 
 * @member {String} html_description
 */
TeamResponseAllOf.prototype['html_description'] = undefined;

/**
 * @member {module:model/WorkspaceCompact} organization
 */
TeamResponseAllOf.prototype['organization'] = undefined;

/**
 * A url that points directly to the object within Asana.
 * @member {String} permalink_url
 */
TeamResponseAllOf.prototype['permalink_url'] = undefined;

/**
 * The visibility of the team to users in the same organization 
 * @member {module:model/TeamResponseAllOf.VisibilityEnum} visibility
 */
TeamResponseAllOf.prototype['visibility'] = undefined;





/**
 * Allowed values for the <code>visibility</code> property.
 * @enum {String}
 * @readonly
 */
TeamResponseAllOf['VisibilityEnum'] = {

    /**
     * value: "secret"
     * @const
     */
    "secret": "secret",

    /**
     * value: "request_to_join"
     * @const
     */
    "request_to_join": "request_to_join",

    /**
     * value: "public"
     * @const
     */
    "public": "public"
};



export default TeamResponseAllOf;

