/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserTaskListCompact from './UserTaskListCompact';

/**
 * The WorkspaceMembershipResponseAllOf model module.
 * @module model/WorkspaceMembershipResponseAllOf
 * @version 1.0.0
 */
class WorkspaceMembershipResponseAllOf {
    /**
     * Constructs a new <code>WorkspaceMembershipResponseAllOf</code>.
     * @alias module:model/WorkspaceMembershipResponseAllOf
     */
    constructor() { 
        
        WorkspaceMembershipResponseAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WorkspaceMembershipResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WorkspaceMembershipResponseAllOf} obj Optional instance to populate.
     * @return {module:model/WorkspaceMembershipResponseAllOf} The populated <code>WorkspaceMembershipResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WorkspaceMembershipResponseAllOf();

            if (data.hasOwnProperty('user_task_list')) {
                obj['user_task_list'] = UserTaskListCompact.constructFromObject(data['user_task_list']);
            }
            if (data.hasOwnProperty('is_active')) {
                obj['is_active'] = ApiClient.convertToType(data['is_active'], 'Boolean');
            }
            if (data.hasOwnProperty('is_admin')) {
                obj['is_admin'] = ApiClient.convertToType(data['is_admin'], 'Boolean');
            }
            if (data.hasOwnProperty('is_guest')) {
                obj['is_guest'] = ApiClient.convertToType(data['is_guest'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UserTaskListCompact} user_task_list
 */
WorkspaceMembershipResponseAllOf.prototype['user_task_list'] = undefined;

/**
 * Reflects if this user still a member of the workspace.
 * @member {Boolean} is_active
 */
WorkspaceMembershipResponseAllOf.prototype['is_active'] = undefined;

/**
 * Reflects if this user is an admin of the workspace.
 * @member {Boolean} is_admin
 */
WorkspaceMembershipResponseAllOf.prototype['is_admin'] = undefined;

/**
 * Reflects if this user is a guest of the workspace.
 * @member {Boolean} is_guest
 */
WorkspaceMembershipResponseAllOf.prototype['is_guest'] = undefined;






export default WorkspaceMembershipResponseAllOf;

