/**
 * Asana
 * This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Asana);
  }
}(this, function(expect, Asana) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Asana.CustomFieldBaseAllOf();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomFieldBaseAllOf', function() {
    it('should create an instance of CustomFieldBaseAllOf', function() {
      // uncomment below and update the code to test CustomFieldBaseAllOf
      //var instance = new Asana.CustomFieldBaseAllOf();
      //expect(instance).to.be.a(Asana.CustomFieldBaseAllOf);
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new Asana.CustomFieldBaseAllOf();
      //expect(instance).to.be();
    });

    it('should have the property enumOptions (base name: "enum_options")', function() {
      // uncomment below and update the code to test the property enumOptions
      //var instance = new Asana.CustomFieldBaseAllOf();
      //expect(instance).to.be();
    });

    it('should have the property precision (base name: "precision")', function() {
      // uncomment below and update the code to test the property precision
      //var instance = new Asana.CustomFieldBaseAllOf();
      //expect(instance).to.be();
    });

    it('should have the property format (base name: "format")', function() {
      // uncomment below and update the code to test the property format
      //var instance = new Asana.CustomFieldBaseAllOf();
      //expect(instance).to.be();
    });

    it('should have the property currencyCode (base name: "currency_code")', function() {
      // uncomment below and update the code to test the property currencyCode
      //var instance = new Asana.CustomFieldBaseAllOf();
      //expect(instance).to.be();
    });

    it('should have the property customLabel (base name: "custom_label")', function() {
      // uncomment below and update the code to test the property customLabel
      //var instance = new Asana.CustomFieldBaseAllOf();
      //expect(instance).to.be();
    });

    it('should have the property customLabelPosition (base name: "custom_label_position")', function() {
      // uncomment below and update the code to test the property customLabelPosition
      //var instance = new Asana.CustomFieldBaseAllOf();
      //expect(instance).to.be();
    });

    it('should have the property isGlobalToWorkspace (base name: "is_global_to_workspace")', function() {
      // uncomment below and update the code to test the property isGlobalToWorkspace
      //var instance = new Asana.CustomFieldBaseAllOf();
      //expect(instance).to.be();
    });

    it('should have the property hasNotificationsEnabled (base name: "has_notifications_enabled")', function() {
      // uncomment below and update the code to test the property hasNotificationsEnabled
      //var instance = new Asana.CustomFieldBaseAllOf();
      //expect(instance).to.be();
    });

  });

}));
